"""init

Revision ID: f1e917289651
Revises: 
Create Date: 2021-10-07 04:54:17.488555

"""
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e917289651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('discipline_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discipline_created_at'), 'discipline', ['created_at'], unique=False)
    op.create_index(op.f('ix_discipline_created_by'), 'discipline', ['created_by'], unique=False)
    op.create_index(op.f('ix_discipline_discipline_group_id'), 'discipline', ['discipline_group_id'], unique=False)
    op.create_index(op.f('ix_discipline_id'), 'discipline', ['id'], unique=False)
    op.create_index(op.f('ix_discipline_name'), 'discipline', ['name'], unique=False)
    op.create_index(op.f('ix_discipline_updated_at'), 'discipline', ['updated_at'], unique=False)
    op.create_index(op.f('ix_discipline_updated_by'), 'discipline', ['updated_by'], unique=False)
    op.create_table('disciplinegroup',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinegroup_created_at'), 'disciplinegroup', ['created_at'], unique=False)
    op.create_index(op.f('ix_disciplinegroup_created_by'), 'disciplinegroup', ['created_by'], unique=False)
    op.create_index(op.f('ix_disciplinegroup_id'), 'disciplinegroup', ['id'], unique=False)
    op.create_index(op.f('ix_disciplinegroup_name'), 'disciplinegroup', ['name'], unique=False)
    op.create_index(op.f('ix_disciplinegroup_updated_at'), 'disciplinegroup', ['updated_at'], unique=False)
    op.create_index(op.f('ix_disciplinegroup_updated_by'), 'disciplinegroup', ['updated_by'], unique=False)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_created_at'), 'doctor', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctor_created_by'), 'doctor', ['created_by'], unique=False)
    op.create_index(op.f('ix_doctor_discipline_id'), 'doctor', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_doctor_first_name'), 'doctor', ['first_name'], unique=False)
    op.create_index(op.f('ix_doctor_hospital_id'), 'doctor', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctor_id'), 'doctor', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_last_name'), 'doctor', ['last_name'], unique=False)
    op.create_index(op.f('ix_doctor_prefix'), 'doctor', ['prefix'], unique=False)
    op.create_index(op.f('ix_doctor_updated_at'), 'doctor', ['updated_at'], unique=False)
    op.create_index(op.f('ix_doctor_updated_by'), 'doctor', ['updated_by'], unique=False)
    op.create_index(op.f('ix_doctor_user_id'), 'doctor', ['user_id'], unique=False)
    op.create_table('doctorproceduremap',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctorproceduremap_created_at'), 'doctorproceduremap', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_created_by'), 'doctorproceduremap', ['created_by'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_doctor_id'), 'doctorproceduremap', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_id'), 'doctorproceduremap', ['id'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_procedure_id'), 'doctorproceduremap', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_updated_at'), 'doctorproceduremap', ['updated_at'], unique=False)
    op.create_index(op.f('ix_doctorproceduremap_updated_by'), 'doctorproceduremap', ['updated_by'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_at'), 'role', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_created_by'), 'role', ['created_by'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_index(op.f('ix_role_updated_at'), 'role', ['updated_at'], unique=False)
    op.create_index(op.f('ix_role_updated_by'), 'role', ['updated_by'], unique=False)
    op.create_table('rolemodulefunctionmap',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_function_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolemodulefunctionmap_created_at'), 'rolemodulefunctionmap', ['created_at'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_created_by'), 'rolemodulefunctionmap', ['created_by'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_id'), 'rolemodulefunctionmap', ['id'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_module_function_id'), 'rolemodulefunctionmap', ['module_function_id'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_role_id'), 'rolemodulefunctionmap', ['role_id'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_updated_at'), 'rolemodulefunctionmap', ['updated_at'], unique=False)
    op.create_index(op.f('ix_rolemodulefunctionmap_updated_by'), 'rolemodulefunctionmap', ['updated_by'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('id_type_id', sa.Integer(), nullable=False),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remember_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('hospital_node_id', sa.Integer(), nullable=True),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('first_name_thai', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name_thai', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('academic_degree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_thai_address', sa.Boolean(), nullable=False),
    sa.Column('address_house_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_moo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_soi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_road', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_tambon_id', sa.Integer(), nullable=True),
    sa.Column('address_amphoe_id', sa.Integer(), nullable=True),
    sa.Column('address_province_id', sa.Integer(), nullable=True),
    sa.Column('address_other', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('potential', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_accept', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_academic_degree'), 'user', ['academic_degree'], unique=False)
    op.create_index(op.f('ix_user_address_amphoe_id'), 'user', ['address_amphoe_id'], unique=False)
    op.create_index(op.f('ix_user_address_house_number'), 'user', ['address_house_number'], unique=False)
    op.create_index(op.f('ix_user_address_moo'), 'user', ['address_moo'], unique=False)
    op.create_index(op.f('ix_user_address_other'), 'user', ['address_other'], unique=False)
    op.create_index(op.f('ix_user_address_province_id'), 'user', ['address_province_id'], unique=False)
    op.create_index(op.f('ix_user_address_road'), 'user', ['address_road'], unique=False)
    op.create_index(op.f('ix_user_address_soi'), 'user', ['address_soi'], unique=False)
    op.create_index(op.f('ix_user_address_tambon_id'), 'user', ['address_tambon_id'], unique=False)
    op.create_index(op.f('ix_user_avatar_path'), 'user', ['avatar_path'], unique=False)
    op.create_index(op.f('ix_user_birth_date'), 'user', ['birth_date'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_created_by'), 'user', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_discipline_id'), 'user', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_user_document_path'), 'user', ['document_path'], unique=False)
    op.create_index(op.f('ix_user_email_verified_at'), 'user', ['email_verified_at'], unique=False)
    op.create_index(op.f('ix_user_first_name_english'), 'user', ['first_name_english'], unique=False)
    op.create_index(op.f('ix_user_first_name_thai'), 'user', ['first_name_thai'], unique=False)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_hospital_id'), 'user', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_user_hospital_node_id'), 'user', ['hospital_node_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_id_number'), 'user', ['id_number'], unique=False)
    op.create_index(op.f('ix_user_id_type_id'), 'user', ['id_type_id'], unique=False)
    op.create_index(op.f('ix_user_is_thai_address'), 'user', ['is_thai_address'], unique=False)
    op.create_index(op.f('ix_user_last_name_english'), 'user', ['last_name_english'], unique=False)
    op.create_index(op.f('ix_user_last_name_thai'), 'user', ['last_name_thai'], unique=False)
    op.create_index(op.f('ix_user_latitude'), 'user', ['latitude'], unique=False)
    op.create_index(op.f('ix_user_longitude'), 'user', ['longitude'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_policy_accept'), 'user', ['policy_accept'], unique=False)
    op.create_index(op.f('ix_user_potential'), 'user', ['potential'], unique=False)
    op.create_index(op.f('ix_user_remember_token'), 'user', ['remember_token'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_updated_by'), 'user', ['updated_by'], unique=False)
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userfeedback_created_at'), 'userfeedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_created_by'), 'userfeedback', ['created_by'], unique=False)
    op.create_index(op.f('ix_userfeedback_detail'), 'userfeedback', ['detail'], unique=False)
    op.create_index(op.f('ix_userfeedback_feedback_type_id'), 'userfeedback', ['feedback_type_id'], unique=False)
    op.create_index(op.f('ix_userfeedback_id'), 'userfeedback', ['id'], unique=False)
    op.create_index(op.f('ix_userfeedback_updated_at'), 'userfeedback', ['updated_at'], unique=False)
    op.create_index(op.f('ix_userfeedback_updated_by'), 'userfeedback', ['updated_by'], unique=False)
    op.create_index(op.f('ix_userfeedback_user_id'), 'userfeedback', ['user_id'], unique=False)
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userlog_id'), 'userlog', ['id'], unique=False)
    op.create_index(op.f('ix_userlog_user_id'), 'userlog', ['user_id'], unique=False)
    op.create_table('usernotification',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usernotification_created_at'), 'usernotification', ['created_at'], unique=False)
    op.create_index(op.f('ix_usernotification_created_by'), 'usernotification', ['created_by'], unique=False)
    op.create_index(op.f('ix_usernotification_detail'), 'usernotification', ['detail'], unique=False)
    op.create_index(op.f('ix_usernotification_id'), 'usernotification', ['id'], unique=False)
    op.create_index(op.f('ix_usernotification_is_read'), 'usernotification', ['is_read'], unique=False)
    op.create_index(op.f('ix_usernotification_name'), 'usernotification', ['name'], unique=False)
    op.create_index(op.f('ix_usernotification_updated_at'), 'usernotification', ['updated_at'], unique=False)
    op.create_index(op.f('ix_usernotification_updated_by'), 'usernotification', ['updated_by'], unique=False)
    op.create_index(op.f('ix_usernotification_user_id'), 'usernotification', ['user_id'], unique=False)
    op.create_table('userphone',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receive_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userphone_created_at'), 'userphone', ['created_at'], unique=False)
    op.create_index(op.f('ix_userphone_created_by'), 'userphone', ['created_by'], unique=False)
    op.create_index(op.f('ix_userphone_detail'), 'userphone', ['detail'], unique=False)
    op.create_index(op.f('ix_userphone_id'), 'userphone', ['id'], unique=False)
    op.create_index(op.f('ix_userphone_number'), 'userphone', ['number'], unique=False)
    op.create_index(op.f('ix_userphone_receive_sms'), 'userphone', ['receive_sms'], unique=False)
    op.create_index(op.f('ix_userphone_updated_at'), 'userphone', ['updated_at'], unique=False)
    op.create_index(op.f('ix_userphone_updated_by'), 'userphone', ['updated_by'], unique=False)
    op.create_index(op.f('ix_userphone_user_id'), 'userphone', ['user_id'], unique=False)
    op.create_table('userrole',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userrole_created_at'), 'userrole', ['created_at'], unique=False)
    op.create_index(op.f('ix_userrole_created_by'), 'userrole', ['created_by'], unique=False)
    op.create_index(op.f('ix_userrole_id'), 'userrole', ['id'], unique=False)
    op.create_index(op.f('ix_userrole_role_id'), 'userrole', ['role_id'], unique=False)
    op.create_index(op.f('ix_userrole_updated_at'), 'userrole', ['updated_at'], unique=False)
    op.create_index(op.f('ix_userrole_updated_by'), 'userrole', ['updated_by'], unique=False)
    op.create_index(op.f('ix_userrole_user_id'), 'userrole', ['user_id'], unique=False)
    op.create_table('usersource',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersource_created_at'), 'usersource', ['created_at'], unique=False)
    op.create_index(op.f('ix_usersource_created_by'), 'usersource', ['created_by'], unique=False)
    op.create_index(op.f('ix_usersource_id'), 'usersource', ['id'], unique=False)
    op.create_index(op.f('ix_usersource_name'), 'usersource', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersource_name'), table_name='usersource')
    op.drop_index(op.f('ix_usersource_id'), table_name='usersource')
    op.drop_index(op.f('ix_usersource_created_by'), table_name='usersource')
    op.drop_index(op.f('ix_usersource_created_at'), table_name='usersource')
    op.drop_table('usersource')
    op.drop_index(op.f('ix_userrole_user_id'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_updated_by'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_updated_at'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_role_id'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_id'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_created_by'), table_name='userrole')
    op.drop_index(op.f('ix_userrole_created_at'), table_name='userrole')
    op.drop_table('userrole')
    op.drop_index(op.f('ix_userphone_user_id'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_updated_by'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_updated_at'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_receive_sms'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_number'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_id'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_detail'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_created_by'), table_name='userphone')
    op.drop_index(op.f('ix_userphone_created_at'), table_name='userphone')
    op.drop_table('userphone')
    op.drop_index(op.f('ix_usernotification_user_id'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_updated_by'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_updated_at'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_name'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_is_read'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_id'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_detail'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_created_by'), table_name='usernotification')
    op.drop_index(op.f('ix_usernotification_created_at'), table_name='usernotification')
    op.drop_table('usernotification')
    op.drop_index(op.f('ix_userlog_user_id'), table_name='userlog')
    op.drop_index(op.f('ix_userlog_id'), table_name='userlog')
    op.drop_table('userlog')
    op.drop_index(op.f('ix_userfeedback_user_id'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_updated_by'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_updated_at'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_id'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_feedback_type_id'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_detail'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_created_by'), table_name='userfeedback')
    op.drop_index(op.f('ix_userfeedback_created_at'), table_name='userfeedback')
    op.drop_table('userfeedback')
    op.drop_index(op.f('ix_user_updated_by'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_remember_token'), table_name='user')
    op.drop_index(op.f('ix_user_potential'), table_name='user')
    op.drop_index(op.f('ix_user_policy_accept'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_longitude'), table_name='user')
    op.drop_index(op.f('ix_user_latitude'), table_name='user')
    op.drop_index(op.f('ix_user_last_name_thai'), table_name='user')
    op.drop_index(op.f('ix_user_last_name_english'), table_name='user')
    op.drop_index(op.f('ix_user_is_thai_address'), table_name='user')
    op.drop_index(op.f('ix_user_id_type_id'), table_name='user')
    op.drop_index(op.f('ix_user_id_number'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_hospital_node_id'), table_name='user')
    op.drop_index(op.f('ix_user_hospital_id'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_first_name_thai'), table_name='user')
    op.drop_index(op.f('ix_user_first_name_english'), table_name='user')
    op.drop_index(op.f('ix_user_email_verified_at'), table_name='user')
    op.drop_index(op.f('ix_user_document_path'), table_name='user')
    op.drop_index(op.f('ix_user_discipline_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_by'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_birth_date'), table_name='user')
    op.drop_index(op.f('ix_user_avatar_path'), table_name='user')
    op.drop_index(op.f('ix_user_address_tambon_id'), table_name='user')
    op.drop_index(op.f('ix_user_address_soi'), table_name='user')
    op.drop_index(op.f('ix_user_address_road'), table_name='user')
    op.drop_index(op.f('ix_user_address_province_id'), table_name='user')
    op.drop_index(op.f('ix_user_address_other'), table_name='user')
    op.drop_index(op.f('ix_user_address_moo'), table_name='user')
    op.drop_index(op.f('ix_user_address_house_number'), table_name='user')
    op.drop_index(op.f('ix_user_address_amphoe_id'), table_name='user')
    op.drop_index(op.f('ix_user_academic_degree'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rolemodulefunctionmap_updated_by'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_updated_at'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_role_id'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_module_function_id'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_id'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_created_by'), table_name='rolemodulefunctionmap')
    op.drop_index(op.f('ix_rolemodulefunctionmap_created_at'), table_name='rolemodulefunctionmap')
    op.drop_table('rolemodulefunctionmap')
    op.drop_index(op.f('ix_role_updated_by'), table_name='role')
    op.drop_index(op.f('ix_role_updated_at'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_created_by'), table_name='role')
    op.drop_index(op.f('ix_role_created_at'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_doctorproceduremap_updated_by'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_updated_at'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_procedure_id'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_id'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_doctor_id'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_created_by'), table_name='doctorproceduremap')
    op.drop_index(op.f('ix_doctorproceduremap_created_at'), table_name='doctorproceduremap')
    op.drop_table('doctorproceduremap')
    op.drop_index(op.f('ix_doctor_user_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_updated_by'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_updated_at'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_prefix'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_last_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_hospital_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_first_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_discipline_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_created_by'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_created_at'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_disciplinegroup_updated_by'), table_name='disciplinegroup')
    op.drop_index(op.f('ix_disciplinegroup_updated_at'), table_name='disciplinegroup')
    op.drop_index(op.f('ix_disciplinegroup_name'), table_name='disciplinegroup')
    op.drop_index(op.f('ix_disciplinegroup_id'), table_name='disciplinegroup')
    op.drop_index(op.f('ix_disciplinegroup_created_by'), table_name='disciplinegroup')
    op.drop_index(op.f('ix_disciplinegroup_created_at'), table_name='disciplinegroup')
    op.drop_table('disciplinegroup')
    op.drop_index(op.f('ix_discipline_updated_by'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_updated_at'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_name'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_id'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_discipline_group_id'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_created_by'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_created_at'), table_name='discipline')
    op.drop_table('discipline')
    # ### end Alembic commands ###
